### PR TITLE
Game content

### PR DESCRIPTION
**Pull request by Veradictus**
Contains changelog from v2.3.3 and v2.3.4

- Mining skill
- Drop tables (mobs now roll through a drop table)
- Magic is now publicly available
- Added support for in-game special ranks
- Added new quests, bosses, weapons, rings, pendants, and areas
- Fixes to disconnection issues due to high-latency
- Fixes and updates to multiple interfaces
- Improvements to clicking moving mobs and ranged combat
- Combat formula and defense stats of mobs updated
- Support for multiple game worlds now completed
- Added arrows to archery
- Added boots
- Added following functionality
- Right-click interaction with mobs and items
- Zooming now available on mobile
- Fixes player stuck online bug
- Fixes bug where items would disappear when unequipping
- Fixes and improvements to the user interface
- Fixes WASD interaction with NPCs/mobs
- Backend fixes and improvements

### CODE REVIEW

**Review by lemueldls — DISMISSED** [review]

**Comment by Veradictus** [comment]
@lemueldls plzzzzz

**Comment by Veradictus** [comment]
@lemueldls plzzzz

**Review by lemueldls — DISMISSED** [review]
k

**Review by lemueldls — APPROVED** [review]

**Pull request merged**
